### ISSUE TITLE
호스팅 관련

### ISSUE THREAD

**Issue by mkthefreeman** [team-requin/Template_1#1]
닷홈 호스팅등을 사용하여 다른 사람 또는, 팀원들이 쉽게 사이트 상태등을 확인 할 수 있도록 호스팅을 하나 올려주세요.
Hosting Sample / Dothome .etc

**Comment by LeagueLugas** [comment]
추후 닷홈 호스팅을 이용하여 웹 페이지를 오픈할 예정입니다.
